import canonicalLaneMathlib.AdmissibleClass
import HautevilleHouse.GeometricLanglandsProgramAlgebroGeometricCanonicalLaneLean.HeckeStack
import HautevilleHouse.GeometricLanglandsProgramAlgebroGeometricCanonicalLaneLean.HitchinFibration
import HautevilleHouse.GeometricLanglandsProgramAlgebroGeometricCanonicalLaneLean.GeometricSatake

namespace HautevilleHouse
namespace GeometricLanglandsProgramAlgebroGeometricCanonicalLaneLean

def ConstrainedGeometricLanglandsClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_geometric_langlands_endgame (A : AdmissibleClass) :
    ConstrainedGeometricLanglandsClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end GeometricLanglandsProgramAlgebroGeometricCanonicalLaneLean
end HautevilleHouse
